# Generated by Django 5.1.4 on 2025-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='video_link',
            field=models.ImageField(blank=True, null=True, upload_to='messages/videos/'),
        ),
    ]
