# Generated by Django 5.1.4 on 2025-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversations', '0002_messages_image_link_messages_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
