# Generated by Django 5.1.6 on 2025-02-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_posts_created_at_posts_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video_link',
        ),
        migrations.AddField(
            model_name='posts',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video_path',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
