# Generated by Django 5.1.6 on 2025-02-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_posts_image_link_remove_posts_video_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image_path',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='video_path',
            new_name='video_link',
        ),
    ]
