# Generated by Django 5.1.4 on 2025-02-26 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
