# Generated by Django 5.1.6 on 2025-02-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avatars', '0001_initial'),
        ('Profiles', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Avatars.avatars'),
        ),
    ]
