# Generated by Django 5.1.6 on 2025-02-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_users_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='avatar',
            new_name='profile_picture',
        ),
    ]
