# Generated by Django 5.1.4 on 2025-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_users_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
